version: "3.1"
services:
  redis:
    image: redis:alpine
    container_name: yu-redis
  mysql:
    image: mysql:8.0
    container_name: yu-mysql
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - ./mysql/mysql-files/:/var/lib/mysql-files/
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3311:3306"
  nginx:
    image: nginx
    container_name: yu-nginx
    working_dir: /application
    volumes:
      - ../../:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "22:22"
  php-fpm:
    build: php
    container_name: yu-php-fpm
    working_dir: /application
    privileged: true
    volumes:
      - ../../:/application

