version: "3.1"
services:
  nginx:
    image: nginx
    container_name: yu-nginx
    working_dir: /application
    volumes:
      - ../../:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:80"
  php-fpm:
    build: php
    container_name: yu-php-fpm
    working_dir: /application
    volumes:
      - ../../:/application

