version: "3.1"
services:
#    php-fpm:
#      image: php:7.4-fpm
#      volumes:
#        - ../../wamp/www:/var/www/html
    nginx:
      image: nginx
      container_name: yu-nginx
#      working_dir: /application
      volumes:
#        - .:/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "9090:80"
